### ISSUE TITLE
Eslint not giving error on missing File

### ISSUE THREAD

**Issue by smartprix** [smartprix/sm-utils#20]
Eslint does not give any error even if `File` is not defined. Might be a bug in eslint.

**Comment by smartprix** [comment]
Same problem with `Cache`

**Comment by rohit-smpx** [comment]
ts-check catches these btw

**Comment by rohit-smpx** [comment]
Because of this : https://github.com/eslint/eslint/issues/9937

**Comment by rohit-smpx** [comment]
Should move this to https://github.com/smartprix/js_conventions
